import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {randomBytes} from 'node:crypto';
import {mkdtemp,writeFile,readFile,stat,unlink,rm,mkdir,open,rename} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {fork,type ChildProcess} from 'node:child_process';
import {createBetaGate,passwordHash} from '../../experiments/private-beta/gate.ts';
import {stagingTLS} from './tls.ts';
const tls=await stagingTLS(),root=await mkdtemp(join(tmpdir(),'gl-tls-security-')),out=resolve('artifacts/private-beta-staging');await mkdir(out,{recursive:true});
const proxyKey=randomBytes(32).toString('hex'),password=randomBytes(24).toString('hex'),salt=randomBytes(16).toString('hex'),administrators=['alice','bob'].map(id=>({id,salt,passwordHash:passwordHash(password,salt)}));
const upstreamHeaders:string[][]=[];let gate:ReturnType<typeof createBetaGate>;const upstream=createServer((req,res)=>{upstreamHeaders.push(Object.keys(req.headers).filter(k=>k==='forwarded'||k.startsWith('x-forwarded-')));if(!gate){res.writeHead(503);res.end();return;}void gate.handler(req,res).catch(()=>{if(!res.destroyed)res.end();});});await new Promise<void>(r=>upstream.listen(0,'127.0.0.1',r));const port=(upstream.address() as {port:number}).port;
const proxy=await tls.proxy(`127.0.0.1:${port}`,proxyKey);let clock=Date.now(),calls=0;
const options={enabled:true,origin:proxy.origin,proxyKey,administrators,storeRoot:join(root,'beta'),protectedRoots:[process.cwd()],cooldownMs:0,now:()=>clock,transport:async(_url:string,init?:RequestInit)=>{calls++;return new Promise<Response>((_r,reject)=>init?.signal?.addEventListener('abort',()=>reject(new Error('cancelled')),{once:true}));}};
const children:ChildProcess[]=[];const receipt:Record<string,unknown>={level:'local TLS staging only',verification:'pending',lineageClaim:'none'};
const post=(path:string,data:unknown,cookie='')=>proxy.client(path,{method:'POST',body:JSON.stringify(data),headers:{origin:proxy.origin,'content-type':'application/json','x-gitlineage-csrf':'1',cookie}});
async function login(identity:string){const r=await post('/api/private-beta/login',{identity,password});assert.equal(r.status,200);assert.match(r.headers['set-cookie']![0]!,/__Host-gl_beta=.*Secure/);return r.headers['set-cookie']![0]!.split(';')[0]!;}
try{
 gate=createBetaGate(options);const defaultProxy=await tls.proxy(`127.0.0.1:${port}`,proxyKey,false);await defaultProxy.client('/api/deep-search/capabilities');assert.ok(upstreamHeaders.some(keys=>keys.includes('x-forwarded-for')));await defaultProxy.stop();upstreamHeaders.length=0;const start=Date.now();await assert.rejects(proxy.client('/healthz',{trust:false}));await assert.rejects(proxy.client('/healthz',{servername:'wrong.invalid'}));
 assert.equal((await post('/api/deep-search/search',{repository:'root/example'})).status,401);
 assert.equal((await fetch(`http://127.0.0.1:${port}/api/deep-search/capabilities`,{headers:{host:new URL(proxy.origin).host}})).status,403);
 await assert.rejects(proxy.client('/api/deep-search/capabilities',{headers:{host:'evil.invalid'}}));assert.equal((await proxy.client('/api/deep-search/capabilities',{headers:{host:'localhost:1'}})).status,403);
 const forgedHeaders:Record<string,string>[]=[{forwarded:'for=127.0.0.1'},{'x-forwarded-for':'127.0.0.1'},{'x-gitlineage-proxy':'forged'}];for(const headers of forgedHeaders)assert.equal((await proxy.client('/api/deep-search/capabilities',{headers})).status,403);
 assert.equal((await proxy.client('/api/deep-search/capabilities',{headers:{'x-forwarded-custom':'forged'}})).status,403);upstreamHeaders.length=0;
 const alice=await login('alice'),bob=await login('bob');for(const headers of [{origin:'https://wrong.invalid'},{origin:proxy.origin,'x-gitlineage-csrf':'0'},{origin:proxy.origin,'content-type':'text/plain'}])assert.equal((await proxy.client('/api/deep-search/search',{method:'POST',body:'{}',headers:{cookie:alice,'content-type':'application/json','x-gitlineage-csrf':'1',...headers}})).status,403);
 assert.equal((await post('/api/private-beta/login',{identity:'alice',password:'invalid'})).status,401);assert.equal(calls,0);assert.equal(gate.usage().reservedAttempts,0);assert.equal(gate.usage().active,0);receipt.invalidRequestsNoWork=true;const a=JSON.parse((await post('/api/deep-search/search',{repository:'root/example'},alice)).body);assert.equal((await post('/api/deep-search/search',{repository:'root/example'},alice)).status,429);const b=JSON.parse((await post('/api/deep-search/search',{repository:'other/example'},bob)).body);
 assert.equal(gate.usage().active,2);assert.equal(gate.usage().reservedAttempts,48);
 assert.equal((await post('/api/deep-search/search',{repository:'root/example'},alice)).status,429);
 assert.equal((await proxy.client('/api/deep-search/tasks/'+a.id,{headers:{cookie:bob}})).status,400);assert.equal((await post('/api/deep-search/tasks/'+a.id+'/cancel',{},bob)).status,400);
 await post('/api/deep-search/tasks/'+a.id+'/cancel',{},alice);await post('/api/deep-search/tasks/'+b.id+'/cancel',{},bob);await new Promise(r=>setTimeout(r,100));assert.equal(gate.usage().reservedAttempts,48);
 const rotated=await login('alice');assert.equal((await proxy.client('/api/deep-search/capabilities',{headers:{cookie:alice}})).status,401);
 const c=JSON.parse((await post('/api/deep-search/search',{repository:'root/example'},rotated)).body);await new Promise(r=>setTimeout(r,10200));const timed=JSON.parse((await proxy.client('/api/deep-search/tasks/'+c.id,{headers:{cookie:rotated}})).body);assert.equal(timed.state,'partial');assert.equal(gate.usage().reservedAttempts,72);clock+=900001;assert.equal((await proxy.client('/api/deep-search/tasks/'+c.id,{headers:{cookie:rotated}})).status,401);
 assert.equal((await stat(join(root,'beta'))).uid,process.getuid!());assert.equal((await stat(join(root,'beta'))).mode&0o777,0o700);assert.equal((await stat(join(root,'beta/state.json'))).mode&0o777,0o600);
 const serialized=await readFile(join(root,'beta/state.json'));const syncDurations:number[]=[];for(let i=0;i<20;i++){const begin=performance.now(),temporary=join(root,'sync.tmp'),destination=join(root,'sync.json');const file=await open(temporary,'wx',0o600);try{await file.writeFile(serialized);await file.sync();}finally{await file.close();}await rename(temporary,destination);const directory=await open(root,'r');try{await directory.sync();}finally{await directory.close();}syncDurations.push(performance.now()-begin);}syncDurations.sort((a,b)=>a-b);receipt.syncMeasurement={samples:20,bytes:serialized.length,p50Ms:syncDurations[9],p95Ms:syncDurations[18],scope:'separate temp-file measurement of file fsync + rename + directory fsync, not power-loss proof'};
 assert.ok(upstreamHeaders.every(keys=>keys.length===0));receipt.https={defaultCaddyForwardingObserved:true,strippedUpstreamHeaders:true,trustedChain:true,untrustedChainRejected:true,rejections:true,rotation:true,expiry:true,peakActive:2,reserved:72,providerCalls:calls,elapsedMs:Date.now()-start,stateBytes:(await stat(join(root,'beta/state.json'))).size,storeUid:(await stat(join(root,'beta'))).uid,directoryMode:'0700',stateMode:'0600'};
 await gate.close();gate=createBetaGate({...options,transport:async()=>{calls++;return new Response('{}',{status:429,headers:{'x-ratelimit-remaining':'0','retry-after':'60'}});}});assert.equal(gate.usage().reservedAttempts,72);const fresh=await login('bob');const d=JSON.parse((await post('/api/deep-search/search',{repository:'other/example'},fresh)).body);await new Promise(r=>setTimeout(r,100));assert.equal(gate.usage().reservedAttempts,96);assert.equal((await post('/api/deep-search/search',{repository:'root/example'},await login('alice'))).status,429);assert.equal((await post('/api/private-beta/logout',{},fresh)).status,200);assert.equal((await proxy.client('/api/deep-search/capabilities',{headers:{cookie:fresh}})).status,401);await gate.close();
 const providerBlocks=[];for(const status of [403,429]){gate=createBetaGate({...options,storeRoot:join(root,'provider-'+status),transport:async()=>{calls++;return new Response('{}',{status,headers:{'x-ratelimit-remaining':'0','retry-after':'60'}});}});const before:number=calls,providerCookie=await login('alice');await post('/api/deep-search/search',{repository:'root/example'},providerCookie);await new Promise(r=>setTimeout(r,100));const otherCookie=await login('bob');assert.equal((await post('/api/deep-search/search',{repository:'other/example'},otherCookie)).status,429);assert.equal(calls-before,1);assert.equal(gate.usage().reservedAttempts,24);providerBlocks.push({status,reserved:24,providerCalls:1,otherIdentityBlocked:true});await gate.close();}receipt.providerBlocks=providerBlocks;
 gate=createBetaGate({...options,storeRoot:join(root,'failed-store')});const failureCookie=await login('alice'),callsBeforeFailure=calls;await rm(join(root,'failed-store/state.json'));await mkdir(join(root,'failed-store/state.json'));for(let i=0;i<2;i++)assert.equal((await post('/api/deep-search/search',{repository:'root/example'},failureCookie)).status,400);assert.equal(calls,callsBeforeFailure);assert.equal(gate.usage().active,0);await assert.rejects(gate.close(),/persistence unavailable/);receipt.persistenceFailure={admissionDenied:true,providerCalls:0};
 // Graceful restart and SIGKILL use a real separate process with its own private store.
 await new Promise<void>(r=>upstream.close(()=>r()));const configPath=join(root,'process.json');const config={...options,now:undefined,transport:undefined,storeRoot:join(root,'process-store'),port};await writeFile(configPath,JSON.stringify(config),{mode:0o600});
 function startChild(){const child=fork(resolve('test/staging/service.ts'),[configPath],{stdio:['ignore','ignore','ignore','ipc']});children.push(child);return {child,ready:new Promise<void>((r,j)=>{child.once('message',()=>r());child.once('exit',()=>j(new Error('isolated service startup refused')));})};}
 let processService=startChild();await processService.ready;const token=await login('alice');const task=JSON.parse((await post('/api/deep-search/search',{repository:'root/example'},token)).body);assert.equal((JSON.parse(await readFile(join(root,'process-store/state.json'),'utf8'))).reserved,24);
 const duplicate=startChild();await assert.rejects(duplicate.ready);receipt.serviceProcess={rssKiB:Number((await readFile(`/proc/${processService.child.pid}/status`,'utf8')).match(/VmRSS:\s+(\d+)/)?.[1]),statCPUFields:(await readFile(`/proc/${processService.child.pid}/stat`,'utf8')).split(' ').slice(13,15).map(Number),note:'Linux CPU ticks at interruption, not CPU hard budget'};processService.child.kill('SIGKILL');await new Promise(r=>processService.child.once('exit',r));assert.ok(await stat(join(root,'process-store/instance.lock')));const blocked=startChild();await assert.rejects(blocked.ready);
 // Confirmed child exit is the prerequisite for this operator recovery step.
 await unlink(join(root,'process-store/instance.lock'));processService=startChild();await processService.ready;const restartedToken=await login('alice');const recovered=JSON.parse((await proxy.client('/api/deep-search/tasks/'+task.id,{headers:{cookie:restartedToken}})).body);assert.equal(recovered.state,'partial');assert.match(recovered.error,/restarted/);assert.equal(JSON.parse(await readFile(join(root,'process-store/state.json'),'utf8')).reserved,24);
 processService.child.kill('SIGTERM');await new Promise(r=>processService.child.once('exit',r));processService=startChild();await processService.ready;assert.equal(JSON.parse(await readFile(join(root,'process-store/state.json'),'utf8')).reserved,24);processService.child.kill('SIGTERM');await new Promise(r=>processService.child.once('exit',r));
 receipt.recovery={SIGKILL:true,staleLockRefused:true,duplicateRefused:true,operatorConfirmedExit:true,partial:true,retainedReservation:24,gracefulRestart:true,powerLoss:'not tested'};
 const memory=process.memoryUsage();receipt.harnessResources={cpu:process.cpuUsage(),rss:memory.rss,note:'harness process totals, not engine hard isolation'};
 receipt.caddy={version:'2.10.2',startupMs:proxy.startupMs,...await proxy.resources()};receipt.proxyResponses=tls.responses;await writeFile(join(out,'security-receipt.json'),JSON.stringify(receipt,null,2));console.log('Trusted HTTPS isolation, quotas and real process recovery passed');
}finally{for(const child of children)if(child.exitCode===null&&child.signalCode===null){child.kill('SIGKILL');await new Promise(r=>child.once('exit',r));}await proxy.stop();await gate!.close().catch(()=>{});upstream.close();await tls.close();await rm(root,{recursive:true,force:true});}
