import {test} from 'node:test';
import assert from 'node:assert/strict';
import {runSnapshotDiscovery,validateEndToEnd} from '../../src/discovery/e2e.ts';
import {mockFixture,FIXED_TIME} from '../../experiments/discovery-v2/phase1c-mock.ts';
import {stableJSON} from '../../src/discovery/offline.ts';
import {sha256} from '../../src/discovery/snapshot.ts';
test('fixed Search → stable ID → full commit → verified blobs → v1 comparison → deterministic sidecar',async()=>{
 const f=mockFixture();const r=await runSnapshotDiscovery(f.plan,{transport:f.transport,now:()=>FIXED_TIME});validateEndToEnd(r.content);
 assert.equal(r.content.coverage.completed,3);assert.equal(r.content.candidates[0]?.comparison?.similarity.find(m=>m.method==='strict_token5')?.score,1);assert.equal(r.content.candidates[2]?.lineageClaim,'none');assert.equal(r.content.candidates[2]?.comparison?.verification.state,'pending');assert.equal(r.content.usage.attempts,17);assert.equal(r.content.usage.searchAttempts,1);assert.equal(r.content.usage.activeWorkers,0);
 assert.equal(r.receipt.contentDigest,sha256(stableJSON(r.content)));const g=mockFixture();const replay=await runSnapshotDiscovery(g.plan,{transport:g.transport,now:()=>FIXED_TIME});assert.equal(r.receipt.contentDigest,replay.receipt.contentDigest);
});
import {SNAPSHOT_PROFILE,SNAPSHOT_NETWORK} from '../../src/discovery/resolution.ts';
import {comparableCandidate} from '../../src/discovery/e2e.ts';
function single(){const f=mockFixture();f.repos.splice(2);f.rebuild();return f;}
async function run(f:ReturnType<typeof mockFixture>,options:Parameters<typeof runSnapshotDiscovery>[1]={}){const r=await runSnapshotDiscovery(f.plan,{transport:f.transport,now:()=>FIXED_TIME,...options});validateEndToEnd(r.content);return r;}
function failed(r:Awaited<ReturnType<typeof run>>,reason:RegExp){const c=r.content.candidates[0]!;assert.equal(c.state,'inconclusive');assert.ok(c.reasons.some(x=>reason.test(x)),JSON.stringify(c.reasons));assert.ok(c.comparison===null||c.comparison.coverage.state!=='completed');assert.equal(c.lineageClaim,'none');assert.equal(c.verification,'pending');assert.equal(r.content.usage.activeWorkers,0);return c;}
test('ID collision remains an actual inconclusive sidecar',async()=>{const f=single();f.routes.set('/repositories/2',{id:99,full_name:'old/example',html_url:'https://github.com/old/example',default_branch:'main'});const r=await run(f);failed(r,/ID mismatch/);assert.equal(r.content.candidates[0]!.resolution.identity,null);assert.ok(!f.calls.includes('/repositories/2/commits/main'));});
test('observed rename and transfer preserve true aliases, stale Search name resolves by ID',async()=>{const f=single();f.repos[1]!.name='transferred/newname';f.rebuild();const r=await run(f);const c=r.content.candidates[0]!;assert.equal(c.state,'completed');assert.equal(c.resolution.identity?.fullName,'transferred/newname');assert.deepEqual(c.resolution.identity?.aliases,['old/example']);assert.equal(c.resolution.observations.length,2);assert.ok(c.resolution.reasons.includes('search_metadata_name_disagreement'));assert.ok(!JSON.stringify(r.content).includes('observedAt'));assert.equal(r.receipt.resolution[1]!.observations[1]!.observedAt,FIXED_TIME);});
test('same repository name with another ID is never merged',async()=>{const f=single();f.repos[1]!.searchName='root/example';f.rebuild();const r=await run(f);failed(r,/name_id_collision/);assert.equal(r.content.candidates[0]!.repositoryId,2);});
test('branch HEAD moves and canonical name changes after resolution: pinned content unchanged',async()=>{const f=single();const transport=async(url:string,init:Parameters<typeof f.transport>[1])=>{const result=await f.transport(url,init);if(url.endsWith('/commits/main')){const old=f.routes.get('/repositories/2/commits/main') as any;f.routes.set('/repositories/2/commits/main',{...old,sha:'f'.repeat(40)});f.repos[1]!.name='later/name';}return result;};const r=await run(f,{transport});assert.equal(r.content.candidates[0]!.resolution.identity?.revision,f.repos[1]!.revision);assert.equal(r.content.candidates[0]!.comparison?.similarity[0]?.score,1);assert.equal(f.calls.filter(c=>c==='/repositories/2/commits/main').length,1);assert.ok(f.calls.filter(c=>c.includes('/git/')).every(c=>/[a-f0-9]{40}$/.test(c)));});
test('wrong version blob response is rejected without similarity=0',async()=>{const f=single();const key=[...f.routes.keys()].find(k=>k.startsWith('/repositories/2/git/blobs/'))!;f.routes.set(key,{...(f.routes.get(key) as any),sha:'f'.repeat(40)});const r=await run(f);assert.deepEqual(failed(r,/blob identity/).comparison?.similarity,[]);});
test('actual Git blob bytes and caller-pinned SHA256 both verified',async()=>{for(const mode of ['blob','digest']){const f=single();const key=[...f.routes.keys()].find(k=>k.startsWith('/repositories/2/git/blobs/'))!;if(mode==='blob'){const b=f.routes.get(key) as any;f.routes.set(key,{...b,content:Buffer.from('x'.repeat(b.size)).toString('base64')});}const r=await run(f,mode==='digest'?{selections:{'2':[{path:'index.js',reason:'known source digest',expectedDigest:'0'.repeat(64)}]}}:{});failed(r,mode==='blob'?/Git blob digest mismatch/:/SHA-256 digest mismatch/);assert.equal(r.content.candidates[0]!.source.bindings.length,0);}});
test('invalid UTF8 stays partial with no source score',async()=>{const f=single();f.repos[1]!.files={'index.js':Buffer.concat([Buffer.from('export const bad = '),Buffer.from([0xff]),Buffer.from(';\n')])};f.rebuild();const r=await run(f);const c=failed(r,/invalid UTF-8/);assert.equal(c.source.coverage.state,'partial');assert.deepEqual(c.comparison?.similarity,[]);});
test('oversized file is denied before blob request or allocation',async()=>{const f=single();f.repos[1]!.files={'index.js':Buffer.alloc(131073,32)};f.rebuild();const r=await run(f);failed(r,/bytesPerFile exhausted/);assert.equal(r.content.candidates[0]!.source.materializedBytes,0);assert.ok(!f.calls.some(c=>c.startsWith('/repositories/2/git/blobs/')));});
test('truncated tree retains selected measurements but partial overall coverage',async()=>{const f=single();const key=[...f.routes.keys()].find(k=>k.startsWith('/repositories/2/git/trees/'))!;f.routes.set(key,{...(f.routes.get(key) as any),truncated:true});const r=await run(f);const c=failed(r,/tree truncated/);assert.equal(c.source.coverage.treeTruncated,true);assert.equal(c.summary?.strict.score,null);assert.equal(c.comparison?.similarity.find(m=>m.method==='strict_token5')?.score,1);});
test('network reservations span Search and snapshot phases without budget reset',async()=>{const f=single();const r=await run(f,{network:{...SNAPSHOT_NETWORK,totalResponseBytes:5*32768}});failed(r,/network bytes exhausted/);assert.equal(r.content.usage.attempts,5);assert.equal(r.content.network.reservedBytes,5*32768);assert.equal(f.calls.length,5);assert.equal(r.content.usage.searchAttempts,1);});
test('cancel in-flight metadata request settles sidecar, releases slots and aborts transport',async()=>{const f=single(),controller=new AbortController();let aborted=false;const r=await run(f,{signal:controller.signal,transport:async(url,init)=>{if(url.endsWith('/repositories/2'))return await new Promise<Response>((_,reject)=>{init.signal.addEventListener('abort',()=>{aborted=true;reject(new Error('aborted'));});setTimeout(()=>controller.abort(),5);});return f.transport(url,init);}});failed(r,/cancelled/);assert.equal(aborted,true);assert.ok(r.content.requests.snapshot.some(r=>r.outcome==='cancelled'));});
test('real comparison worker deadline retains no fake zero or leaked worker',async()=>{const f=single();const r=await run(f,{workerWallMs:1});const c=failed(r,/deadline exhausted/);assert.deepEqual(c.comparison?.similarity,[]);assert.equal(c.summary,null);assert.equal(r.content.usage.activeWorkers,0);});
test('filtered and absent selected source are inconclusive, never negative',async()=>{for(const mode of ['filtered','absent']){const f=single();f.repos[1]!.files=mode==='filtered'?{'index.js':Buffer.from('// @generated DO NOT EDIT\nexport const a = 123;\n')}:{'other.js':Buffer.from('export const b = 12345;\n')};f.rebuild();const r=await run(f);const c=failed(r,mode==='filtered'?/filtered generated|no eligible source/:/selected path unavailable/);assert.equal(c.comparison?.similarity.length,0);assert.equal(c.summary,null);}});
test('one completed candidate survives another inaccessible repository',async()=>{const f=mockFixture();f.routes.delete('/repositories/3');const r=await run(f);assert.equal(r.content.coverage.completed,2);assert.equal(r.content.coverage.inconclusive,1);assert.equal(r.content.candidates[0]!.state,'completed');assert.equal(r.content.candidates[1]!.resolution.identity,null);assert.equal(r.content.candidates[2]!.state,'completed');assert.equal(r.content.candidates[1]!.summary,null);});
test('unknown exact match remains pending and has no Graph relationship collection',async()=>{const f=single();f.repos[1]!.label='unknown';const r=await run(f);const c=r.content.candidates[0]!;assert.equal(c.state,'completed');assert.equal(c.comparison?.similarity[0]?.score,1);assert.equal(c.lineageClaim,'none');assert.deepEqual(c.comparison?.verification.canonicalEvidenceIds,[]);assert.ok(!('relationships' in c));const injected=structuredClone(r.content) as any;injected.relationships=[];assert.throws(()=>validateEndToEnd(injected),/prohibited|shape/);});
test('replays with different real clocks and rate limit headers have the same content hash',async()=>{const f=single();const r=await run(f);const g=single();const replay=await run(g,{now:()=> '2026-10-10T00:00:00.000Z',transport:async(url,init)=>{const response=await g.transport(url,init);response.headers.set('x-ratelimit-remaining','10');return response;}});assert.equal(r.receipt.contentDigest,replay.receipt.contentDigest);assert.notEqual(r.receipt.startedAt,replay.receipt.startedAt);});
test('commit missing/deleted/short/full fixed-target mismatch fail closed',async()=>{for(const kind of ['branch','commit404','short','targetMismatch']){const f=single();if(kind==='branch')f.routes.set('/repositories/2',{...(f.routes.get('/repositories/2') as any),default_branch:null});if(kind==='commit404')f.routes.delete('/repositories/2/commits/main');if(kind==='short')f.routes.set('/repositories/2/commits/main',{sha:'abc',commit:{tree:{sha:'a'.repeat(40)}},parents:[]});if(kind==='targetMismatch'){const key=`/repositories/1/commits/${f.plan.target.revision}`;f.routes.set(key,{...(f.routes.get(key) as any),sha:'9'.repeat(40)});}const r=await run(f);failed(r,kind==='targetMismatch'?/adapter requires/:kind==='branch'?/default branch unavailable/:kind==='commit404'?/http_error/:/invalid full commit/);assert.equal(r.content.candidates[0]!.summary,null);}});
test('parser failure keeps exact observation and unavailable tokens, no negative label',async()=>{const f=single();f.repos[1]!.files={'index.js':Buffer.from('export function broken( { return ; invalid syntax longer than twenty }')};f.rebuild();const r=await run(f);const c=failed(r,/parse_failed/);assert.equal(c.comparison?.similarity.find(m=>m.method==='strict_token5')?.score,null);assert.equal(c.comparison?.similarity.find(m=>m.method==='strict_token5')?.state,'unavailable');assert.equal(c.summary?.strict.score,null);});
test('invalid tree hash rejects substituted version',async()=>{const f=single();const key=[...f.routes.keys()].find(k=>k.startsWith('/repositories/2/git/trees/'))!;const b=f.routes.get(key) as any;f.routes.set(key,{...b,tree:b.tree.map((e:any)=>({...e,sha:'e'.repeat(40)}))});const r=await run(f);failed(r,/Git tree digest mismatch/);assert.equal(r.content.candidates[0]!.source.bindings.length,0);});
test('attempt ceiling and source total ceiling are enforced in actual sidecar',async()=>{for(const profile of [{...SNAPSHOT_PROFILE,attempts:5},{...SNAPSHOT_PROFILE,totalBytes:100}]){const f=single();const r=await run(f,{profile});failed(r,/attempts exhausted|totalBytes exhausted/);assert.ok(r.content.usage.attempts<=profile.attempts);assert.ok(r.content.usage.totalBytes<=profile.totalBytes);}});
test('response overflow cancels stream and retains only complete bounded chunks',async()=>{const f=single();let cancelled=false;const r=await run(f,{network:{perResponseBytes:2048,totalResponseBytes:1048576},transport:async(url,init)=>{if(url.endsWith('/repositories/2'))return new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(2049));},cancel(){cancelled=true;}}));return f.transport(url,init);}});failed(r,/response_bytes_exhausted/);assert.equal(cancelled,true);assert.ok(r.content.network.receivedBytes>r.content.network.retainedBytes);assert.ok(r.content.network.overflowBytes>0);});
test('rate-limit wait and redirect stop further snapshot HTTP requests',async()=>{for(const status of [200,302,429]){const f=single();const r=await run(f,{transport:async(url,init)=>{if(url.endsWith('/repositories/2')){if(status===200){const result=await f.transport(url,init);result.headers.set('retry-after','60');return result;}return new Response('',{status,headers:{location:'https://evil.invalid','retry-after':'60'}});}return f.transport(url,init);}});failed(r,/provider stopped|redirect_rejected|rate_limit/);assert.ok(!f.calls.includes('/repositories/2/commits/main'));}});
test('all Phase1C hard caps reject expansion before first network request',async()=>{for(const [field,value] of Object.entries({attempts:25,candidates:4,filesPerCandidate:9,bytesPerFile:131073,totalBytes:2097153,wallMs:30001,concurrency:3,searchAttempts:5})){const f=single();await assert.rejects(run(f,{profile:{...SNAPSHOT_PROFILE,[field]:value}}),/ceiling/);assert.equal(f.calls.length,0);}});
import {BudgetLedger} from '../../src/discovery/budget.ts';
import {NetworkLedger} from '../../src/discovery/network.ts';
import {RepositorySnapshotResolver} from '../../src/discovery/resolution.ts';
import {discoverRepositories} from '../../src/discovery/search.ts';
import {collectSources,gitTree} from '../../src/discovery/source-collection.ts';
import {validateCandidate} from '../../src/discovery/contract.ts';
test('v2 conversion validates live source bindings; unchanged v1 rejects unresolved candidates',async()=>{
 const f=single(),ledger=new BudgetLedger(SNAPSHOT_PROFILE),network=new NetworkLedger(ledger,SNAPSHOT_NETWORK),options={transport:f.transport,now:()=>FIXED_TIME};const search=await discoverRepositories(f.plan,options,network);const unresolved=search.candidates[0]!;assert.throws(()=>validateCandidate(unresolved));
 const resolver=new RepositorySnapshotResolver(network,{...options,historicalRoutes:true}),target=await resolver.resolve(1,[],f.plan.target.revision),candidate=await resolver.resolve(2,unresolved.candidate.observations),first=await collectSources(target,[{path:'index.js',reason:'entry'}],resolver),second=await collectSources(candidate,[{path:'index.js',reason:'entry'}],resolver);
 const comparable=comparableCandidate(unresolved,target,candidate,first,second,ledger);validateCandidate(comparable);assert.equal(comparable.schemaVersion,'discovery-candidate@1');assert.equal(comparable.similarity.length,0);
 second.bindings[0]!.revision='f'.repeat(40);assert.throws(()=>comparableCandidate(unresolved,target,candidate,first,second,ledger),/version or binding mismatch/);second.bindings[0]!.revision=candidate.identity!.revision;
 second.snapshot!.sources[0]!.content+=' ';assert.throws(()=>comparableCandidate(unresolved,target,candidate,first,second,ledger),/source content digest mismatch/);
});
test('explicit nested tree selection stays pinned and unsupported paths have reasons',async()=>{
 const f=single(),bytes=f.repos[1]!.files['index.js']!,blob=sha256(bytes);const entry={path:'entry.ts',type:'blob',mode:'100644',sha:[...f.routes.keys()].find(k=>k.startsWith('/repositories/2/git/blobs/'))!.split('/').at(-1)!,size:bytes.length};const nested=gitTree([entry]),rootEntries=[{path:'src',type:'tree',mode:'040000',sha:nested}],root=gitTree(rootEntries);
 const old=f.routes.get('/repositories/2/commits/main') as any;f.routes.set('/repositories/2/commits/main',{...old,commit:{tree:{sha:root}}});f.routes.set(`/repositories/2/git/trees/${root}`,{sha:root,truncated:false,tree:rootEntries});f.routes.set(`/repositories/2/git/trees/${nested}`,{sha:nested,truncated:false,tree:[entry]});
 const r=await run(f,{selections:{'2':[{path:'src/entry.ts',reason:'explicit supported module',expectedDigest:blob}]}});assert.equal(r.content.candidates[0]!.state,'completed');assert.equal(r.content.candidates[0]!.source.bindings[0]!.path,'src/entry.ts');assert.equal(r.content.candidates[0]!.source.selections[0]!.reason,'explicit supported module');assert.equal(r.content.usage.attempts,10);
});
test('export validator rejects revision, digest, alias and schema drift',async()=>{
 const f=single();const r=await run(f);
 for(const mutation of [(c:any)=>{c.candidates[0].source.bindings[0].revision='a'.repeat(40);},(c:any)=>{c.candidates[0].resolution.identity.aliases=['guessed/name'];},(c:any)=>{c.candidates[0].source.snapshot.files[0].digest='a'.repeat(64);},(c:any)=>{c.candidateSchema='discovery-candidate@2';},(c:any)=>{c.candidates[0].score=1;}]){const copy=structuredClone(r.content);mutation(copy);assert.throws(()=>validateEndToEnd(copy));}
});
