import {randomBytes} from 'node:crypto';
import {stagingTLS} from '../staging/tls.ts';
import {createServer} from 'node:http';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {fixtureServer,A} from './fixture-server.ts';
import {createBetaGate,passwordHash} from '../../experiments/private-beta/gate.ts';
import {treeFixture} from '../discovery/tree-fixture.ts';
import {validatePreviewExport} from '../../experiments/discovery-v2/preview-contract.ts';
import {cacheProof} from './cache-proof.ts';
const tls=process.env.GITLINEAGE_STAGING_TLS==='1'?await stagingTLS():undefined;
const out=resolve(tls?'artifacts/private-beta-staging':'artifacts/private-beta');await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,...(tls?{env:{...process.env,HOME:tls.home}}:{})});const results=[];
try{for(const width of [390,430,1280,1920]){
 const root=await mkdtemp(join(tmpdir(),'gl-beta-browser-')),fixture=treeFixture();if(tls){for(const repo of fixture.repos)repo.files['helper.ts']=Buffer.from('export const helper = (value: number) => value + 1;\n');fixture.rebuild();}let gate:ReturnType<typeof createBetaGate>;
 const proxyKey=tls?randomBytes(32).toString('hex'):undefined;const app=await fixtureServer({privateBetaProxyKey:proxyKey,privateBetaHandler:async(req,res)=>gate.handler(req,res)});
 const upstreamURL=app.url;const proxy=tls?await tls.proxy(new URL(app.url).host,proxyKey!):undefined;if(proxy)app.url=proxy.origin;
 const salt='b'.repeat(32);gate=createBetaGate({enabled:true,origin:app.url,proxyKey,administrators:[{id:'admin',salt,passwordHash:passwordHash('browser-only-secret',salt)}],storeRoot:join(root,'beta'),protectedRoots:[app.fixtureCacheRoot,process.cwd()],transport:fixture.transport,cooldownMs:0});
 const context=await browser.newContext({viewport:{width,height:900},isMobile:width<768,hasTouch:width<768,reducedMotion:'reduce',acceptDownloads:true}),page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 try{
 await page.goto(app.url+'/'+A);await page.locator('#canvas .node-hit').first().waitFor();assert.equal(await page.locator('#deep-launch').count(),0);
 if(tls){assert.equal((await fetch(upstreamURL+'/'+A)).status,403);}const cache=await cacheProof(app.fixtureCacheRoot);assert.equal((tls?(await proxy!.client('/api/deep-search/search',{method:'POST',body:JSON.stringify({repository:'root/example'}),headers:{'content-type':'application/json'}})).status:(await page.request.post(app.url+'/api/deep-search/search',{data:{repository:'root/example'}})).status()),403);assert.equal(fixture.calls.length,0);
 const loginResponse=await page.goto(app.url+'/private-beta');assert.match(loginResponse!.headers()['content-security-policy']!,/frame-ancestors 'none'/);assert.equal(loginResponse!.headers()['x-frame-options'],'DENY');await page.locator('[name=identity]').fill('admin');await page.locator('[name=password]').fill('browser-only-secret');await page.locator('#login button').click();await page.waitForURL(app.url+'/');if(tls){const cookies=await context.cookies();const session=cookies.find(c=>c.name==='__Host-gl_beta');assert.ok(session?.secure&&session.httpOnly&&session.sameSite==='Strict');await assert.rejects(proxy!.client('/healthz',{trust:false}));}
 const workspaceResponse=await page.goto(app.url+'/'+A);assert.match(workspaceResponse!.headers()['content-security-policy']!,/frame-ancestors 'none'/);assert.equal(workspaceResponse!.headers()['x-frame-options'],'DENY');
 const attacker=createServer((_req,res)=>res.end(`<iframe src="${app.url}/${A}"></iframe><iframe src="${app.url}/private-beta"></iframe>`));await new Promise<void>(r=>attacker.listen(0,'127.0.0.1',r));const embedded=await context.newPage();try{await embedded.goto(`http://127.0.0.1:${(attacker.address() as {port:number}).port}`);await embedded.waitForTimeout(500);for(const frame of embedded.frames().slice(1))assert.equal(await frame.locator('#login, #canvas, #deep-launch').count(),0);}finally{await embedded.close();await new Promise<void>(r=>attacker.close(()=>r()));}
 await page.locator('#deep-launch').waitFor();await page.locator('#canvas .node-hit').first().waitFor();await page.waitForTimeout(300);await page.locator('#canvas .plate-row').first().focus();await page.keyboard.press('Enter');await page.waitForURL(u=>u.searchParams.has('edge'),{timeout:5000});const measure=()=>page.locator('#canvas').evaluate(el=>{const svg=el as unknown as SVGSVGElement,m=svg.getScreenCTM();return {ctm:m?[m.a,m.b,m.c,m.d,m.e,m.f].map(v=>Number(v.toFixed(4))):null,selection:new URL(location.href).searchParams.get('edge'),viewBox:svg.getAttribute('viewBox')};});const graphState=await measure();assert.ok(graphState.ctm&&graphState.selection);const url=page.url(),viewBox=await page.locator('#canvas').getAttribute('viewBox');
 await page.locator('#deep-launch').click();await page.locator('#deep-repository').fill('root/example');await page.locator('#deep-search-submit').click();await page.locator('#deep-candidates input').first().waitFor();await page.locator('#deep-candidates input').last().check();await page.locator('#deep-source-preview').click();await page.locator('#deep-files input').first().waitFor();if(tls)for(const box of await page.locator('#deep-files input').all())await box.check();const fileChoice=page.locator('#deep-files input').first();await fileChoice.uncheck();if(!tls)await fileChoice.check();if(tls)await page.screenshot({path:join(out,width+'-sources.png'),fullPage:true});
 await page.locator('#deep-compare').click();await page.locator('#deep-results .deep-measurement').first().waitFor({timeout:10000});assert.match(await page.locator('#deep-results').innerText(),/pending/);
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#deep-download').click()]);const path=join(out,width+'-sidecar.json');await download.saveAs(path);const exported=JSON.parse(await readFile(path,'utf8'));validatePreviewExport(exported);if(tls){assert.ok(exported.selection!.selected.some((r:any)=>r.paths.length>1));}const downloaded=await readFile(path,'utf8');assert.ok(!downloaded.includes('browser-only-secret'));if(proxyKey)assert.ok(!downloaded.includes(proxyKey));for(const cookie of await context.cookies())assert.ok(!downloaded.includes(cookie.value));
 await page.screenshot({path:join(out,width+'-comparison.png'),fullPage:true});await page.locator('#deep-back').click();assert.equal(page.url(),url);assert.equal(await page.locator('#canvas').getAttribute('viewBox'),viewBox);assert.deepEqual(await measure(),graphState);assert.equal(await page.locator('#deep-launch').evaluate(el=>el===document.activeElement),true);assert.deepEqual(await cacheProof(app.fixtureCacheRoot),cache);await page.locator('#deep-launch').click();await page.locator('#deep-sign-out').click();await page.waitForURL(app.url+'/private-beta');assert.equal((tls?(await proxy!.client('/api/deep-search/capabilities')).status:(await page.request.get(app.url+'/api/deep-search/capabilities')).status()),401);assert.deepEqual(errors,[]);results.push({width,status:'pass',graphStateUnchanged:true,focusRestored:true,requests:fixture.calls.length,verification:'pending',lineageClaim:'none'});
 }finally{await context.close();await gate.close();await proxy?.stop();await app.cleanup();await rm(root,{recursive:true,force:true});}
}}finally{await browser.close();await tls?.close();}await writeFile(join(out,'validation.json'),JSON.stringify({engine:'Chromium simulation',results},null,2));console.log('Private Beta browser acceptance passed',results);
